version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: trabalho
      MYSQL_ROOT_PASSWORD: sua_senha
    ports:
      - "8111:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8112:8112"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_NAME=trabalho
      - DB_USER=appuser
      - DB_PASSWORD=appsenha
      - DB_HOST=db
      - DB_PORT=3306
      - PORT=8112

volumes:
  db_data: