version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: trabalho
      MYSQL_ROOT_PASSWORD: sua_senha
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_NAME=trabalho
      - DB_USER=root
      - DB_PASSWORD=sua_senha
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  db_data: