version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: trabalho
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsenha
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8111:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    container_name: deploy-app
    restart: always
    environment:
      DB_NAME: trabalho
      DB_USER: appuser
      DB_PASSWORD: appsenha
      DB_HOST: db
      DB_PORT: 3306
      PORT: 8112
    ports:
      - "8112:8112"
    depends_on:
      - db
volumes:
  db_data: